title: Lotse
description: A personal blog
url: ""
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:slug

kramdown:
  math_engine: mathjax
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
